[tool.poetry]
name = "pytyt"
version = "0.1.0"
description = ""
authors = ["jumaniyozov <jumaniyozovse@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
asyncio = "^3.4.3"
aiohttp = "^3.7.3"
aiodns = "^2.0.0"
uvicorn = {extras = ["standard"], version = "^0.13.3"}
Django = "^3.1.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
